version: '3'
services:
  node:
    container_name: node
    build: .
    ports:
      - "80:80"
      - "49153:49153"
    volumes:
      - .:/app:rw
      - "/app/node_modules"
  postgres:
    container_name: database
    image: postgres:14.2-alpine
    environment:
      POSTGRES_DB: "database"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .pgdata:/var/lib/postgresql/data/pgdata:Z
    ports:
      - "5432:5432"
