version: '3'
services:
  node:
    build: .
    ports:
      - "4200:4200"
      - "49153:49153"
    volumes:
      - .:/app:rw
      - "/app/node_modules"
  postgres:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_DB: "fsafsaf"
      POSTGRES_USER: "gasgas"
      POSTGRES_PASSWORD: "APSDADW$@$!Fgeg"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"